title: digits
description: A template for quickly starting Meteor application development
google_analytics:
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0

gems:
  - jekyll-mentions
